version: '3'

services:
  app:
    image: next-image
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/src/app/pages
      - ./public:/src/app/public
      - ./styles:/src/app/styles