FROM node:alpine

WORKDIR /src/app

COPY package.json yarn.lock  ./

RUN yarn install
COPY next.config.js .

COPY pages ./pages
COPY public ./public
COPY styles ./styles

EXPOSE 3002
EXPOSE 49153

CMD ["yarn", "dev -p 3002"]