FROM node:16-alpine

USER node

RUN mkdir /home/node/client

WORKDIR /home/node/client

CMD "sleep" "5" &&\
    "echo" "next is up..."  &&\
    "npm" "i" &&\
    "npm" "run" "build" &&\
    "npm" "run" "start"