FROM node:16.16.0

WORKDIR /src/app

COPY package.json ./
COPY yarn.lock ./
COPY next.config.js .

RUN yarn install

COPY pages ./pages
COPY public ./public
COPY styles ./styles

EXPOSE 3002
EXPOSE 49153

CMD ["yarn", "dev -p 3002"]