version: '3.8'

services:
  transcendence_api:
    container_name: "transcendence_api"
    restart: always
    depends_on:
      - transcendence_db
    build:
      context: ./backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/home/node/app
    env_file:
      - ./backend/.env.app.dev
    networks:
      - backend-net

  transcendence_db:
    container_name: "transcendence_db"
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.db.dev
    networks:
      - backend-net

  transcendence_adminer:
    container_name: "transcendence_adminer"
    image: adminer
    ports:
      - 9000:8080
    links:
      - "transcendence_db:db"
    depends_on:
      - transcendence_db
    networks:
      - backend-net
    restart: always
  
  redis_auth_session:
    container_name: "transcendence_redis"
    image: redis:alpine
    networks:
      - backend-net
    restart: always


volumes:
  postgres-data:

networks:
  backend-net:
